global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # Backend metrics
  - job_name: "backend"
    static_configs:
      - targets: ["mehediimun.duckdns.org:5000"]

  # Prometheus self-monitoring
  - job_name: "prometheus"
    static_configs:
      - targets: ["13.228.167.171:9090"]   # Replace localhost with infra IP

  # RabbitMQ metrics
  - job_name: "rabbitmq"
    static_configs:
      - targets: ["13.228.167.171:15692"]  # Replace localhost with infra IP
