global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
# Backend metrics
- job_name: "backend"
  static_configs:
  - targets: [ "3.1.47.175:5000" ]

# Prometheus self-monitoring
- job_name: "prometheus"
  static_configs:
  - targets: [ "3.1.47.175:9090" ]

# RabbitMQ metrics
- job_name: "rabbitmq"
  static_configs:
  - targets: [ "3.1.47.175:15672" ] # RabbitMQ management port
